services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    env_file:
      - .env
  sms-modem:
    build: ./sms-modem
    depends_on:
      - rabbitmq
    volumes:
      - /dev:/dev
    privileged: true
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      SERIAL_PORT: ${SERIAL_PORT:-/dev/ttyUSB0}
    env_file:
      - .env
  sms-processor:
    build: ./sms-processor
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
    env_file:
      - .env
  api-service:
    build: ./api-service
    depends_on:
      - rabbitmq
    ports:
      - "${API_PORT:-5000}:${API_PORT:-5000}"
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
    env_file:
      - .env