version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
  sms-modem:
    build: ./sms-modem
    depends_on:
      - rabbitmq
    volumes:
      - /dev:/dev
    privileged: true
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - SERIAL_PORT=${SERIAL_PORT}
  sms-processor:
    build: ./sms-processor
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
  api-service:
    build: ./api-service
    depends_on:
      - rabbitmq
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      
