name: Docker Registry Login Test

on:
  workflow_dispatch: # Запуск вручную

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Verify Login
        run: echo "Docker login successful!"
# Пустая строка без пробелов